### PR TITLE
UART whitespace and coding style fixes

### PR DESCRIPTION
**Pull request by wallento**
No functional changes

### CODE REVIEW

**Comment by imphil** [comment]
if done with the changes, please fold into one commit and push. Thanks.

**Comment by wallento** [comment]
Why fold? It keeps discussion history not to fold.

**Comment by imphil** [comment]
I don't see the relevance in discussion history to be part of the revision history (it's already present in the pull request and in the discussion here). I see, however, value in individually bisectable, easy to read commits. Reading gets much harder if much of the code read is already outdated again in the next commit.

**Comment by wallento** [comment]
Whatever..

**Pull request merged**
